name: Funnel
options:
  bundleIdPrefix: com.joya
  deploymentTarget:
    iOS: 17.0
  createIntermediateGroups: true
  generateEmptyDirectories: true
settings:
  base:
    MARKETING_VERSION: 1.0.0
    CURRENT_PROJECT_VERSION: 1
    DEVELOPMENT_TEAM: 6L379HCV5Q
targets:
  Funnel:
    type: application
    platform: iOS
    sources:
      - path: Funnel
        createIntermediateGroups: true
    resources:
      - path: Funnel/Resources
        type: folder
        createIntermediateGroups: true
      - path: Funnel/Funnel/Assets.xcassets
    info:
      path: Funnel/Info.plist
      properties:
        UIAppFonts:
          - "Nunito-Black.ttf"
          - "Nunito-BlackItalic.ttf"
          - "Nunito-Bold.ttf"
          - "Nunito-BoldItalic.ttf"
          - "Nunito-ExtraBold.ttf"
          - "Nunito-ExtraBoldItalic.ttf"
          - "Nunito-ExtraLight.ttf"
          - "Nunito-ExtraLightItalic.ttf"
          - "Nunito-Italic.ttf"
          - "Nunito-Light.ttf"
          - "Nunito-LightItalic.ttf"
          - "Nunito-Medium.ttf"
          - "Nunito-MediumItalic.ttf"
          - "Nunito-Regular.ttf"
          - "Nunito-SemiBold.ttf"
          - "Nunito-SemiBoldItalic.ttf"
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
          NSAllowsLocalNetworking: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.joya.funnel
        DEVELOPMENT_TEAM: 6L379HCV5Q
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations: UIInterfaceOrientationPortrait
        INFOPLIST_KEY_UISupportedInterfaceOrientations~ipad: "UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown"
        SWIFT_EMIT_LOC_STRINGS: YES
        SWIFT_VERSION: 5.0
        INFOPLIST_KEY_NSMicrophoneUsageDescription: "Funnel needs access to your microphone to record voice notes."